### ISSUE TITLE
 介绍 PD链接需要权限，不能正常打开

### ISSUE THREAD

**Issue by jiashiwen** [pingcap/presentations#11]
https://docs.google.com/presentation/d/1NxVemycWYriMkim7hYykgdRw1yRPulv_6Bm6xOgvc9s

**Comment by yangwenmai** [comment]
现在已经可以打开使用了

**Comment by siyu-hu** [comment]
更新了最新的 PD 介绍文章：https://pingcap.com/blog-cn/best-practice-pd/
