### ISSUE TITLE
[Paper reading] Pessimistic Cardinality Estimatio b站视频不全  AND  求分享slides

### ISSUE THREAD

**Issue by LumingSun** [pingcap/presentations#32]
[Paper reading] Pessimistic Cardinality Estimatio b站视频不全   
能否分享paper reading的slides呢？

很棒！谢谢！

**Comment by gingerkidney** [comment]
slides 2021 年的分享加上了～ b 站的视频也补全了～

**Comment by LumingSun** [comment]
感谢～

**Comment by LumingSun** [comment]
Paper reading "Everything You Always Wanted to Know About Compiled and Vectorized Queries But Were Afraid to Asks" 的Slides和B站链接放错了诶。
