### ISSUE TITLE
Paper reading render issue

### ISSUE THREAD

**Issue by tisonkun** [pingcap/presentations#51]
https://github.com/pingcap/presentations/blob/master/paper-reading.md

![image](https://user-images.githubusercontent.com/18818196/122235315-2c8f6500-cef0-11eb-8e00-7602fff8bc80.png)

**Comment by Yangxiamao** [comment]
https://github.com/pingcap/presentations/pull/49
I posted a pr to solve this issue five days ago

**Comment by tisonkun** [comment]
closed by #49
